Add Ansible Molecule for role testing
* Use coglinev3/ansible docker imeges with Ansible Molecule

Use the docker images coglinev3/ansible with Ansible Molecule (see
https://hub.docker.com/r/coglinev3/ansible for details)

* Use a new .travis.yml for integrating Ansible Molecule
- use distribution Ubuntu Bionic
- set language to 'minimal'
- install Ansible Molecule with pip
- test role with Ansible Molecule

Remove py3-yaml from Alpine package list

Package py3-yaml was removed from defualt Alpine packæge list to prevent
the following error:
ERROR: py3-yaml-5.3.1-r0: failed to rename
usr/lib/python3.8/site-packages/.apk.70f3aebbbbf2c6946aed2b12a043c3b7e3cf93883a3da651 to usr/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8.egg-info

The PyYAML package is already installed.